# Generated by Django 3.2 on 2021-05-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
